### ISSUE TITLE
Android build crashes on mipad

### ISSUE THREAD

**Issue by kanarena** [Kitteh6660/Corruption-of-Champions-Mod#46]
Normal c.o.c runs fine if that is helpful, revamp immediately crashes on opening, the tablet in question does have an odd aspect ratio and native resolution for an android tab, if either of these details might be contributing, I did attempt running the game after altering the tablet's resolution to match something more standard, but it did not work for this app.

**Comment by Kitteh6660** [comment]
Unfortunately, I have one problem. I don't have Android device.

Android devices vary a lot.

**Comment by Cyrus67** [comment]
I have this same issue with my HTC One. Regrettably I have no experience in either flash or mobile development so I can't do anything other than report it. tits and coc vanilla both work fine for reference.

**Comment by archangel543** [comment]
Same, game crashes on startup, using Android 5.0.1

**Comment by pleaseohgodhelpme** [comment]
Seems it just doesn't agree with android in general. Crashes on startup for me too. Might have something to do with 5.0.1 but i doubt it. Trying on an android tablet next.

**Comment by pleaseohgodhelpme** [comment]
Huh. It works. Carmillo vivitar crap works. Color me surprised. No idea why it even begins to work while my phone cant even start it.

**Comment by kanarena** [comment]
Well, a recent update to my tablet added the option to retrieve error logs on crash, I don't know if it'll help any other device, or even my own but this is the results of using that with the latest revamp apk.

java.lang.UnsatisfiedLinkError: Native method not found: com.adobe.air.AIRWindowSurfaceView.nativeOnFormatChangeListener:(I)V
	at com.adobe.air.AIRWindowSurfaceView.nativeOnFormatChangeListener(Native Method)
	at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:683)
	at android.view.SurfaceView.updateWindow(SurfaceView.java:587)
	at android.view.SurfaceView.access$000(SurfaceView.java:86)
	at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:176)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2008)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1121)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5804)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:762)
	at android.view.Choreographer.doCallbacks(Choreographer.java:575)
	at android.view.Choreographer.doFrame(Choreographer.java:545)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:748)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5028)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dragontamer8740** [comment]
Try updating the adobe AIR runtime on google play. I bet that's it. If not, I have been doing unofficial builds for a while on infinitechan's /f/ board. I've had someone else report success with those. Mine bake in a correct AIR runtime, so the downloads are kind of big (20MB), but they seem to work reliably.
